// Cadastro de usuário
@token = Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRWRkIiwiZW1haWwiOiJFZGRAZ21haWwuY29tIiwiaWF0IjoxNjc0Nzg5NDUyLCJleHAiOjE2NzczODE0NTIsInN1YiI6IjQ1MWRlZGZjLWVlY2UtNDkwYS05NGZkLTFmMDM2ZThlZTdmNCJ9.RaoMEeXC9S9kGgoRVZcBV-qMvN3ETXuBTAoo5pUt_mI

POST  http://localhost:3333/users
content-type: application/json

{
    "name": "Edd",
    "email": "EddD@gmail.com",
    "password": "123456"
}
###
// Login de usuário@
POST  http://localhost:3333/session
content-type: application/json

{
    "email": "Edd@gmail.com",
    "password": "123456"
}
###
GET http://localhost:3333/userInfo
Authorization: {{token}}


// Categorys
###
POST  http://localhost:3333/category
content-type: application/json
Authorization: {{token}}

{
    "name": "Sobremesas"
}

###
GET http://localhost:3333/categories
Authorization: {{token}}
