
@token = Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFuaWxvIiwiZW1haWwiOiJEYW5pbG9AZ21haWwuY29tIiwiaWF0IjoxNjc0ODM5NzE1LCJleHAiOjE2Nzc0MzE3MTUsInN1YiI6ImZiMTZjNzg3LTA4OTctNGI4Yi1iOTVlLWI3N2YyYjVkMTdmNyJ9.s-yI7jzMV1jz1BIUK6gL4zL743_sSvM5Wh_MwKYPWfY

// USERS
POST  http://localhost:3333/users
content-type: application/json

{
    "name": "Danilo",
    "email": "Danilo@gmail.com",
    "password": "123456"
}
###

POST  http://localhost:3333/session
content-type: application/json

{
    "email": "Danilo@gmail.com",
    "password": "123456"
}
###
GET http://localhost:3333/userInfo
Authorization: {{token}}

// CATEGORYS
###
POST  http://localhost:3333/category
content-type: application/json
Authorization: {{token}}

{
    "name": "Comidas"
    "aimg": " "
    
}

###
GET http://localhost:3333/categories
Authorization: {{token}}

// PRODUCTS
###
GET http://localhost:3333/category/product?=389b63ee-aa50-43ea-9cf7-8c685777d94f
Authorization: {{token}}
