
@token = Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFuaWxvIiwiZW1haWwiOiJEYW5pbG9AZ21haWwuY29tIiwiaWF0IjoxNjc0ODM4MTM1LCJleHAiOjE2Nzc0MzAxMzUsInN1YiI6ImZiMTZjNzg3LTA4OTctNGI4Yi1iOTVlLWI3N2YyYjVkMTdmNyJ9.4q-O_r39KomWk1W7OVoimJHeI_TFsDopTVP9QK3eFZQ

// USERS
POST  http://localhost:3333/users
content-type: application/json

{
    "name": "Danilo",
    "email": "Danilo@gmail.com",
    "password": "123456"
}
###

POST  http://localhost:3333/session
content-type: application/json

{
    "email": "Danilo@gmail.com",
    "password": "123456"
}
###
GET http://localhost:3333/userInfo
Authorization: {{token}}

// CATEGORYS
###
POST  http://localhost:3333/category
content-type: application/json
Authorization: {{token}}

{
    "name": "Sobremesas"
}

###
GET http://localhost:3333/categories
Authorization: {{token}}

// PRODUCTS
###
POST http://localhost:3333/product
content-type: application/json
Authorization: {{token}}
